In [ ]:
import numpy as np
dizi=np.array([1,23,53,62,29,61,53],dtype=int)

print("Dizinin Boyutu:",dizi.shape)
print("Dizinin Eleman Sayısı:",dizi.size) #len(dizi)
print()

def soru2(dizi):
    print("------ Dizi Bilgileri ------")
    print("Dizinin Boyutu:",dizi.shape)
    print("Dizinin Satır Sayısı:",dizi.shape[0])
    print("Dizinin Sütun Sayısı:",dizi.shape[1])
    print(dizi[0][2])
    print(dizi[1:])
    print()
    
dizi2=np.array([[1,23,53],[12,43,1]])
dizi3=np.array([[14,3,29],[12,65,9],[11,29,22]])

soru2(dizi2)
soru2(dizi3)

print(dizi[0])
print(dizi[2:6])
print("-----------------")
print(dizi2[1])
print(dizi2[1:])
print("-----------------")
print(dizi3[2])
print(dizi3[1:])

In [10]:
import numpy as np
zeros=np.array([[0,0,0],[0,0,0]])
ones=np.array([[1,1,1],[1,1,1]])
satir=np.concatenate((zeros,ones),axis=0)
sutun=np.concatenate((zeros,ones),axis=1)
print("Satır")
print(satir)
print()
print("Sütun")
print(sutun)

Satır
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]

Sütun
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
